# IoT Configuration
config_iot:
  mqtt:
    server_url: "broker.mqttdashboard.com"
    server_port: 1883
    topic_sub: "eyrc/CeAhsAGA/iot_to_ros"
    topic_pub: "eyrc/CeAhsAGA/ros_to_iot"          
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"
    spread_sheet_id: "1zm6nhfMDdUijzCuldgtv2cyIp10_iwgtioJrOPhRiEk"
