!!python/object/new:moveit_msgs.msg._RobotTrajectory.RobotTrajectory {state: [!!python/object/new:trajectory_msgs.msg._JointTrajectory.JointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, world]}, [ur5_shoulder_pan_joint, ur5_shoulder_lift_joint,
          ur5_elbow_joint, ur5_wrist_1_joint, ur5_wrist_2_joint, ur5_wrist_3_joint],
        [!!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [-2.129258997300613, -1.1170552630694326, -0.4713041428493101,
                -1.5533801668743896, -1.0122786510543698, -5.586867150420005e-05],
              !!python/tuple [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [-0.24313487240936543,
                0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 0]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [-2.129321968627512, -1.1171036895251332, -0.4711499403863919,
                -1.5533084982987333, -1.0123218402218812, -7.609720663167537e-05],
              !!python/tuple [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [0.24313487240936543,
                0.18697652896620923, -0.5953820253283646, -0.27671530609273354, 0.16675514475312417,
                0.0781032026707082], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 22759504]}]}]]}, !!python/object/new:trajectory_msgs.msg._MultiDOFJointTrajectory.MultiDOFJointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, '']}, [], []]}]}
