!!python/object/new:moveit_msgs.msg._RobotTrajectory.RobotTrajectory {state: [!!python/object/new:trajectory_msgs.msg._JointTrajectory.JointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, world]}, [ur5_shoulder_pan_joint, ur5_shoulder_lift_joint,
          ur5_elbow_joint, ur5_wrist_1_joint, ur5_wrist_2_joint, ur5_wrist_3_joint],
        [!!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [2.792436065447614, -2.0070347671178173, 0.06975216999070533,
                -1.2042943407877775, 0.436257900017023, -3.1241456889820647], !!python/tuple [
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [-0.058742645836911696,
                0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 0]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [2.792427031865497, -2.0071167938553627, 0.06989547710332822,
                -1.204238170914439, 0.43635296160288783, -3.1240987811987617], !!python/tuple [
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [0.058742645836911696,
                0.5333950065847861, -0.9318827076208203, -0.3652556575555271, -0.61815667349002,
                -0.3050270939997505], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 17537523]}]}]]}, !!python/object/new:trajectory_msgs.msg._MultiDOFJointTrajectory.MultiDOFJointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, '']}, [], []]}]}
